Repository hove-io/navitia_sdk_docs, pull requests merged in 2023-02, with the labels that each got.

#53 aroundme/2.2.1
  docs/around_me/android/changelogs.md
  docs/around_me/android/releases/2.2.1/index.md
Labels: PR APPROVED 💪

#55 hotfix/show-back-router
  docs/bookmark/android/changelogs.md
  docs/bookmark/android/releases/1.1.2/index.md
  docs/journey/android/changelogs.md
  docs/journey/android/releases/5.2.1/index.md
  docs/traffic/android/changelogs.md
  docs/traffic/android/releases/2.1.1/index.md
Labels: PR APPROVED 💪

#58 task/add-journey-ios-5.2.1
  docs/journey/ios/changelogs.md
  docs/journey/ios/releases/5.2.1/index.md
Labels: DO NOT MERGE ☠️, PR APPROVED 💪

#60 release/5.2.2
  docs/journey/android/changelogs.md
  docs/journey/android/releases/5.2.2/index.md
  docs/journey/ios/changelogs.md
  docs/journey/ios/releases/5.2.2/index.md
Labels: REVIEW REQUIRED 👀

#63 release/15-02
  docs/around_me/android/changelogs.md
  docs/around_me/android/index.md
  docs/around_me/android/releases/2.0.0/index.md
  docs/around_me/android/releases/2.1.0/index.md
  docs/around_me/android/releases/2.3.0/index.md
  docs/around_me/ios/changelogs.md
  docs/around_me/ios/index.md
  docs/around_me/ios/releases/3.1.0/index.md
  docs/around_me/ios/releases/3.2.0/index.md
  docs/assets/img/aroundme_android_poi_button_event.png
  docs/assets/img/aroundme_ios_poi_button_event.png
  docs/assets/img/journey_android_roadmap_button_event.png
  docs/assets/img/journey_ios_roadmap_button_event.png
  docs/bookmark/android/changelogs.md
  docs/bookmark/android/index.md
  docs/bookmark/android/releases/1.1.0/index.md
  docs/bookmark/android/releases/1.2.0/index.md
  docs/bookmark/ios/changelogs.md
  docs/bookmark/ios/index.md
  docs/bookmark/ios/releases/1.1.0/index.md
  docs/getting_started.md
  docs/journey/android/changelogs.md
  docs/journey/android/index.md
  docs/journey/android/releases/5.1.0/index.md
  docs/journey/android/releases/5.2.0/index.md
  docs/journey/android/releases/5.3.0/index.md
  docs/journey/ios/changelogs.md
  docs/journey/ios/index.md
  docs/journey/ios/releases/5.3.0/index.md
  docs/schedule/android/changelogs.md
  docs/schedule/android/index.md
  docs/schedule/android/releases/2.0.0/index.md
  docs/schedule/android/releases/2.1.0/index.md
  docs/schedule/android/releases/2.2.0/index.md
  docs/schedule/ios/changelogs.md
  docs/schedule/ios/index.md
  docs/schedule/ios/releases/3.2.0/index.md
  docs/traffic/android/changelogs.md
  docs/traffic/android/index.md
  docs/traffic/android/releases/2.0.0/index.md
  docs/traffic/android/releases/2.1.0/index.md
  docs/traffic/android/releases/2.1.1/index.md
  docs/traffic/android/releases/2.1.2/index.md
  docs/traffic/ios/changelogs.md
  docs/traffic/ios/index.md
  docs/traffic/ios/releases/3.1.0/index.md
Labels: REVIEW REQUIRED 👀, DO NOT MERGE ☠️

#67 Add journey ios 5.3.2
  docs/journey/ios/changelogs.md
  docs/journey/ios/index.md
  docs/journey/ios/releases/5.3.2/index.md
Labels: PR APPROVED 💪
