Repository hove-io/navitia_sdk_docs, pull requests merged in 2023-01, with the labels that each got.

#33 release/10-01-22
  docs/around_me/android/changelogs.md
  docs/around_me/android/index.md
  docs/around_me/android/releases/2.1.0/index.md
  docs/around_me/ios/changelogs.md
  docs/around_me/ios/index.md
  docs/around_me/ios/releases/3.1.0/index.md
  docs/expert/android/changelogs.md
  docs/expert/android/index.md
  docs/expert/android/model/VehicleJourneyPositions.md
  docs/expert/android/releases/3.2.1/index.md
  docs/expert/android/releases/3.2.2/index.md
  docs/expert/ios/changelogs.md
  docs/expert/ios/index.md
  docs/expert/ios/model/VehicleJourneyPositions.md
  docs/expert/ios/releases/2.3.3/index.md
  docs/expert/ios/releases/2.3.4/index.md
  docs/getting_started.md
  docs/journey/android/changelogs.md
  docs/journey/android/index.md
  docs/journey/android/releases/5.2.0/index.md
  docs/journey/ios/changelogs.md
  docs/journey/ios/index.md
  docs/journey/ios/releases/5.2.0/index.md
  docs/schedule/android/changelogs.md
  docs/schedule/android/index.md
  docs/schedule/android/releases/2.1.0/index.md
  docs/schedule/ios/changelogs.md
  docs/schedule/ios/index.md
  docs/schedule/ios/releases/3.1.0/index.md
  docs/traffic/android/changelogs.md
  docs/traffic/android/index.md
  docs/traffic/android/releases/2.1.0/index.md
  docs/traffic/ios/changelogs.md
  docs/traffic/ios/index.md
  docs/traffic/ios/releases/3.0.4/index.md
Labels: PR APPROVED 💪

#34 ios - update pod install infos
  docs/around_me/ios/index.md
  docs/journey/ios/index.md
  docs/schedule/ios/index.md
  docs/traffic/ios/index.md
Labels: REVIEW REQUIRED 👀

#36 Task/journey reliable bike
  docs/journey/android/index.md
  docs/journey/ios/index.md
Labels: PR APPROVED 💪

#37 task/schedule
  docs/assets/img/schedule_android_home_favorites_screen.png
  docs/assets/img/schedule_android_station_next_departures_favorites_screen.png
  docs/schedule/android/index.md
  docs/schedule/ios/index.md
Labels: PR APPROVED 💪

#35 Task/bookmark
  docs/assets/img/aroundme_ios_bookmark_node.png
  docs/assets/img/aroundme_ios_bookmark_saving_node.png
  docs/assets/img/aroundme_ios_traffic_node.png
  docs/assets/img/bookmark_android_favorites_screen.png
  docs/assets/img/bookmark_android_go_fromto.png
  docs/assets/img/bookmark_ios_favorites_screen.png
  docs/assets/img/bookmark_ios_go_fromto.png
  docs/assets/img/schedule_android_home_favorites_screen.png
  docs/assets/img/schedule_android_station_next_departures_favorites_screen.png
  docs/bookmark/android/changelogs.md
  docs/bookmark/android/index.md
  docs/bookmark/android/releases/1.1.0/index.md
  docs/bookmark/ios/changelogs.md
  docs/bookmark/ios/index.md
  docs/bookmark/ios/releases/1.0.4/index.md
  docs/bookmark/overview.md
  docs/index.md
  docs/journey/android/index.md
  docs/journey/ios/index.md
  docs/schedule/android/index.md
  docs/schedule/ios/index.md
Labels: PR APPROVED 💪

#38 task/aroundme
  docs/around_me/android/index.md
  docs/around_me/ios/index.md
Labels: REVIEW REQUIRED 👀, DO NOT MERGE ☠️

#42 task/add-schedule-3.1.2
  docs/schedule/ios/changelogs.md
  docs/schedule/ios/releases/3.1.1/index.md
  docs/schedule/ios/releases/3.1.2/index.md
Labels: DO NOT MERGE ☠️, PR APPROVED 💪

#45 task/add-step-by-step-doc
  docs/around_me/android/index.md
  docs/around_me/ios/index.md
  docs/assets/img/journey_android_navigation_screen.png
  docs/assets/img/journey_ios_navigation_screen.png
  docs/journey/android/index.md
  docs/journey/ios/index.md
  docs/schedule/android/index.md
  docs/schedule/ios/index.md
  docs/traffic/android/index.md
  docs/traffic/ios/index.md
Labels: REVIEW REQUIRED 👀, DO NOT MERGE ☠️

#47 task/update-screenshots
  docs/around_me/android/index.md
  docs/around_me/ios/index.md
  docs/assets/img/aroundme_android_bookmark_saving_node.png
  docs/assets/img/aroundme_android_navigating.png
  docs/assets/img/aroundme_android_screen_flow.png
  docs/assets/img/aroundme_android_traffic_button.png
  docs/assets/img/aroundme_ios_bookmark_node.png
  docs/assets/img/aroundme_ios_bookmark_saving_node.png
  docs/assets/img/aroundme_ios_filters_screen.png
  docs/assets/img/aroundme_ios_go_fromto.png
  docs/assets/img/aroundme_ios_map_screen.png
  docs/assets/img/aroundme_ios_navigating.png
  docs/assets/img/aroundme_ios_screen_flow.png
  docs/assets/img/aroundme_ios_search_screen.png
  docs/assets/img/aroundme_ios_traffic_button.png
  docs/assets/img/aroundme_ios_traffic_node.png
  docs/assets/img/journey_android_autocompletion_screen.png
  docs/assets/img/journey_android_journeys_screen.png
  docs/assets/img/journey_android_navigating.png
  docs/assets/img/journey_android_navigation_screen.png
  docs/assets/img/journey_android_roadmap_screen.png
  docs/assets/img/journey_android_screen_flow.png
  docs/assets/img/journey_ios_autocompletion_screen.png
  docs/assets/img/journey_ios_journeys_screen.png
  docs/assets/img/journey_ios_navigating.png
  docs/assets/img/journey_ios_navigation_screen.png
  docs/assets/img/journey_ios_roadmap_screen.png
  docs/assets/img/journey_ios_screen_flow.png
  docs/assets/img/schedule_android_navigating.png
  docs/assets/img/schedule_android_screen_flow.png
  docs/assets/img/schedule_ios_navigating.png
  docs/assets/img/schedule_ios_screen_flow.png
  docs/assets/img/traffic_android_navigating.png
  docs/assets/img/traffic_android_screen_flow.png
  docs/assets/img/traffic_ios_navigating.png
  docs/assets/img/traffic_ios_screen_flow.png
  docs/journey/android/index.md
  docs/journey/ios/index.md
  docs/schedule/android/index.md
  docs/schedule/ios/index.md
  docs/traffic/android/index.md
  docs/traffic/ios/index.md
Labels: PR APPROVED 💪

#48 Develop
  docs/around_me/android/index.md
  docs/around_me/ios/index.md
  docs/assets/img/aroundme_android_bookmark_saving_node.png
  docs/assets/img/aroundme_android_navigating.png
  docs/assets/img/aroundme_android_screen_flow.png
  docs/assets/img/aroundme_android_traffic_button.png
  docs/assets/img/aroundme_ios_bookmark_node.png
  docs/assets/img/aroundme_ios_bookmark_saving_node.png
  docs/assets/img/aroundme_ios_filters_screen.png
  docs/assets/img/aroundme_ios_go_fromto.png
  docs/assets/img/aroundme_ios_map_screen.png
  docs/assets/img/aroundme_ios_navigating.png
  docs/assets/img/aroundme_ios_screen_flow.png
  docs/assets/img/aroundme_ios_search_screen.png
  docs/assets/img/aroundme_ios_traffic_button.png
  docs/assets/img/aroundme_ios_traffic_node.png
  docs/assets/img/journey_android_autocompletion_screen.png
  docs/assets/img/journey_android_journeys_screen.png
  docs/assets/img/journey_android_navigating.png
  docs/assets/img/journey_android_navigation_screen.png
  docs/assets/img/journey_android_roadmap_screen.png
  docs/assets/img/journey_android_screen_flow.png
  docs/assets/img/journey_ios_autocompletion_screen.png
  docs/assets/img/journey_ios_journeys_screen.png
  docs/assets/img/journey_ios_navigating.png
  docs/assets/img/journey_ios_navigation_screen.png
  docs/assets/img/journey_ios_roadmap_screen.png
  docs/assets/img/journey_ios_screen_flow.png
  docs/assets/img/schedule_android_navigating.png
  docs/assets/img/schedule_android_screen_flow.png
  docs/assets/img/schedule_ios_navigating.png
  docs/assets/img/schedule_ios_screen_flow.png
  docs/assets/img/traffic_android_navigating.png
  docs/assets/img/traffic_android_screen_flow.png
  docs/assets/img/traffic_ios_navigating.png
  docs/assets/img/traffic_ios_screen_flow.png
  docs/journey/android/index.md
  docs/journey/ios/index.md
  docs/schedule/android/index.md
  docs/schedule/ios/index.md
  docs/traffic/android/index.md
  docs/traffic/ios/index.md
Labels: REVIEW REQUIRED 👀

#49 task/aroundme-version
  docs/around_me/android/changelogs.md
  docs/around_me/android/releases/2.2.0/index.md
Labels: REVIEW REQUIRED 👀, DO NOT MERGE ☠️

#52 Develop
  docs/around_me/android/index.md
  docs/assets/img/journey_android_journeys_screen_bike_tab.png
  docs/assets/img/journey_ios_journeys_screen_bike_tab.png
  docs/assets/img/schedule_android_home_favorites_screen.png
  docs/assets/img/schedule_ios_home_favorites_screen.png
  docs/assets/img/schedule_ios_station_next_departures_favorites_screen.png
  docs/bookmark/android/changelogs.md
  docs/bookmark/android/releases/1.1.1/index.md
  docs/getting_started.md
  docs/journey/android/index.md
  docs/journey/android/releases/5.2.0/index.md
Labels: PR APPROVED 💪
