Repository hove-io/navitia_sdk_docs, pull requests merged in 2024-07, with the labels that each got.

#130 Add releases
  docs/around_me/android/changelogs.md
  docs/around_me/android/index.md
  docs/around_me/android/releases/2.8.2/index.md
  docs/around_me/ios/changelogs.md
  docs/around_me/ios/index.md
  docs/around_me/ios/releases/3.6.1/index.md
  docs/around_me/ios/releases/3.6.2/index.md
  docs/bookmark/android/changelogs.md
  docs/bookmark/android/index.md
  docs/bookmark/android/releases/1.5.1/index.md
  docs/bookmark/ios/changelogs.md
  docs/bookmark/ios/index.md
  docs/bookmark/ios/releases/1.5.1/index.md
  docs/bookmark/ios/releases/1.5.2/index.md
  docs/expert/android/changelogs.md
  docs/expert/android/index.md
  docs/expert/android/releases/3.5.1/index.md
  docs/expert/ios/changelogs.md
  docs/expert/ios/index.md
  docs/expert/ios/releases/2.7.2/index.md
  docs/journey/android/changelogs.md
  docs/journey/android/index.md
  docs/journey/android/releases/5.12.2/index.md
  docs/journey/android/releases/5.12.3/index.md
  docs/journey/ios/changelogs.md
  docs/journey/ios/index.md
  docs/journey/ios/releases/5.12.0/index.md
  docs/journey/ios/releases/5.12.1/index.md
  docs/schedule/android/changelogs.md
  docs/schedule/android/index.md
  docs/schedule/android/releases/2.7.0/index.md
  docs/schedule/ios/changelogs.md
  docs/schedule/ios/index.md
  docs/schedule/ios/releases/3.5.1/index.md
  docs/schedule/ios/releases/3.6.0/index.md
  docs/schedule/ios/releases/3.6.1/index.md
  docs/traffic/android/changelogs.md
  docs/traffic/android/index.md
  docs/traffic/android/releases/2.5.3/index.md
  docs/traffic/ios/changelogs.md
  docs/traffic/ios/index.md
  docs/traffic/ios/releases/3.5.2/index.md
  docs/traffic/ios/releases/3.5.3/index.md
Labels: PR APPROVED 💪

#131 release/24 06 2024
  docs/around_me/android/changelogs.md
  docs/around_me/android/index.md
  docs/around_me/android/releases/2.8.2/index.md
  docs/around_me/ios/changelogs.md
  docs/around_me/ios/index.md
  docs/around_me/ios/releases/3.6.1/index.md
  docs/around_me/ios/releases/3.6.2/index.md
  docs/bookmark/android/changelogs.md
  docs/bookmark/android/index.md
  docs/bookmark/android/releases/1.5.1/index.md
  docs/bookmark/ios/changelogs.md
  docs/bookmark/ios/index.md
  docs/bookmark/ios/releases/1.5.1/index.md
  docs/bookmark/ios/releases/1.5.2/index.md
  docs/expert/android/changelogs.md
  docs/expert/android/index.md
  docs/expert/android/releases/3.5.1/index.md
  docs/expert/ios/changelogs.md
  docs/expert/ios/index.md
  docs/expert/ios/releases/2.7.2/index.md
  docs/journey/android/changelogs.md
  docs/journey/android/index.md
  docs/journey/android/releases/5.12.2/index.md
  docs/journey/android/releases/5.12.3/index.md
  docs/journey/ios/changelogs.md
  docs/journey/ios/index.md
  docs/journey/ios/releases/5.12.0/index.md
  docs/journey/ios/releases/5.12.1/index.md
  docs/schedule/android/changelogs.md
  docs/schedule/android/index.md
  docs/schedule/android/releases/2.7.0/index.md
  docs/schedule/ios/changelogs.md
  docs/schedule/ios/index.md
  docs/schedule/ios/releases/3.5.1/index.md
  docs/schedule/ios/releases/3.6.0/index.md
  docs/schedule/ios/releases/3.6.1/index.md
  docs/traffic/android/changelogs.md
  docs/traffic/android/index.md
  docs/traffic/android/releases/2.5.3/index.md
  docs/traffic/ios/changelogs.md
  docs/traffic/ios/index.md
  docs/traffic/ios/releases/3.5.2/index.md
  docs/traffic/ios/releases/3.5.3/index.md
Labels: REVIEW REQUIRED 👀, DO NOT MERGE ☠️

#134 releases/25-07-2024/android
  docs/around_me/android/changelogs.md
  docs/around_me/android/index.md
  docs/around_me/android/releases/2.9.0/index.md
  docs/bookmark/android/changelogs.md
  docs/bookmark/android/index.md
  docs/bookmark/android/releases/1.6.0/index.md
  docs/journey/android/changelogs.md
  docs/journey/android/index.md
  docs/journey/android/releases/5.13.0/index.md
  docs/schedule/android/changelogs.md
  docs/schedule/android/index.md
  docs/schedule/android/releases/2.7.1/index.md
  docs/traffic/android/changelogs.md
  docs/traffic/android/index.md
  docs/traffic/android/releases/2.5.4/index.md
Labels: REVIEW REQUIRED 👀

#136 releases/24 07 2024 ios
  docs/around_me/ios/changelogs.md
  docs/around_me/ios/index.md
  docs/around_me/ios/releases/3.7.0/index.md
  docs/bookmark/ios/changelogs.md
  docs/bookmark/ios/index.md
  docs/bookmark/ios/releases/1.6.0/index.md
  docs/journey/ios/changelogs.md
  docs/journey/ios/index.md
  docs/journey/ios/releases/5.13.0/index.md
  docs/schedule/ios/changelogs.md
  docs/schedule/ios/index.md
  docs/schedule/ios/releases/3.7.0/index.md
  docs/traffic/ios/changelogs.md
  docs/traffic/ios/index.md
  docs/traffic/ios/releases/3.5.5/index.md
Labels: REVIEW REQUIRED 👀, DO NOT MERGE ☠️

#137 releases/24 07 2024 ios
  README.md
  docs/around_me/ios/changelogs.md
  docs/around_me/ios/index.md
  docs/around_me/ios/releases/3.7.0/index.md
  docs/bookmark/ios/changelogs.md
  docs/bookmark/ios/index.md
  docs/bookmark/ios/releases/1.6.0/index.md
  docs/journey/ios/changelogs.md
  docs/journey/ios/index.md
  docs/journey/ios/releases/5.13.0/index.md
  docs/schedule/ios/changelogs.md
  docs/schedule/ios/index.md
  docs/schedule/ios/releases/3.7.0/index.md
  docs/traffic/ios/changelogs.md
  docs/traffic/ios/index.md
  docs/traffic/ios/releases/3.5.5/index.md
Labels: REVIEW REQUIRED 👀, DO NOT MERGE ☠️
