Repository hove-io/navitia_sdk_docs, pull requests merged in 2024-10, with the labels that each got.

#149 feature/schedule/2363-2384
  docs/assets/file/config.json
  docs/getting_started.md
Labels: REVIEW REQUIRED 👀

#150 feature/around-me/sdk-2383-2375
  docs/getting_started.md
Labels: REVIEW REQUIRED 👀

#151 task/config/poi-subcategory-types
  docs/assets/file/config.json
  docs/getting_started.md
Labels: REVIEW REQUIRED 👀

#152 android/journey/5.15.0
  docs/journey/android/changelogs.md
  docs/journey/android/index.md
  docs/journey/android/releases/5.15.0/index.md
Labels: REVIEW REQUIRED 👀

#153 android/journey/5.15.0
  docs/journey/android/changelogs.md
  docs/journey/android/index.md
  docs/journey/android/releases/5.15.0/index.md
Labels: REVIEW REQUIRED 👀

#154 feature/SDK 2418
  docs/assets/file/config.json
  docs/getting_started.md
Labels: PR APPROVED 💪

#157 journey/release/5.15.0
  docs/journey/android/changelogs.md
  docs/journey/android/index.md
  docs/journey/android/releases/5.15.0/index.md
  docs/journey/android/releases/5.15.1/index.md
  docs/journey/ios/changelogs.md
  docs/journey/ios/index.md
  docs/journey/ios/releases/5.14.0/index.md
Labels: REVIEW REQUIRED 👀

#158 releases/24 09 2024
  docs/around_me/ios/changelogs.md
  docs/around_me/ios/index.md
  docs/around_me/ios/releases/3.8.0/index.md
  docs/bookmark/ios/changelogs.md
  docs/bookmark/ios/index.md
  docs/bookmark/ios/releases/1.7.0/index.md
  docs/getting_started.md
  docs/journey/ios/changelogs.md
  docs/journey/ios/releases/5.14.0/index.md
  docs/schedule/ios/changelogs.md
  docs/schedule/ios/releases/3.8.0/index.md
  docs/traffic/ios/changelogs.md
  docs/traffic/ios/index.md
  docs/traffic/ios/releases/3.5.6/index.md
Labels: DO NOT MERGE ☠️, PR APPROVED 💪

#159 releases/24 09 2024
  docs/around_me/ios/changelogs.md
  docs/around_me/ios/index.md
  docs/around_me/ios/releases/3.8.0/index.md
  docs/bookmark/ios/changelogs.md
  docs/bookmark/ios/index.md
  docs/bookmark/ios/releases/1.7.0/index.md
  docs/getting_started.md
  docs/journey/ios/changelogs.md
  docs/journey/ios/releases/5.14.0/index.md
  docs/schedule/ios/changelogs.md
  docs/schedule/ios/releases/3.8.0/index.md
  docs/traffic/ios/changelogs.md
  docs/traffic/ios/index.md
  docs/traffic/ios/releases/3.5.6/index.md
Labels: REVIEW REQUIRED 👀, DO NOT MERGE ☠️

#162 Fix links in table, add disruptions color
  docs/getting_started.md
Labels: REVIEW REQUIRED 👀, DO NOT MERGE ☠️

#163 task/clean doc
  docs/getting_started.md
Labels: REVIEW REQUIRED 👀, DO NOT MERGE ☠️

#164 feature/sdk-2451-2452
  docs/assets/file/config.json
  docs/getting_started.md
Labels: PR APPROVED 💪

#166 feature/sdk-2494-2495
  docs/assets/file/config.json
  docs/getting_started.md
Labels: REVIEW REQUIRED 👀

#167 feature/sdk-2503-2505
  docs/assets/file/config.json
  docs/getting_started.md
Labels: PR APPROVED 💪
